# try
`try` blocks. exceptions are thrown from a `try` block.
`catch` clause are exception handlers.

`try {`
`	program-statements`
`}	catch(exception-declaration) {`
`	handler-statements`
`} 	catch(exception-declaration) {`
`	handler-statements`
`} //...`


2021/12/06::16:11